#stk-azure-to-aws-restapi-private
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CopyAzureToAWS API - REST API Private

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "General Tag Settings"
        Parameters:
          - Environment
          - Client
          - Project
          - SubProject
          - Description
          - Owner
          - CreatedBy
          - UpdatedBy
      - Label:
          default: "Configuration for Secret Manager Resource Creation"
        Parameters:
          - PostgresConnectionUSReaderString
          - PostgresConnectionUSWriterString
          - PostgresConnectionCAReaderString
          - PostgresConnectionCAWriterString
      - Label:
          default: "General Configuration"
        Parameters:
          - SecretName
      - Label:
          default: "VPC, Subnets, SecurityGroups Configuration for Azure to AWS Lambda(s) "
        Parameters:
          - VpcId
          - SubnetIds
          - SecurityGroupIds
          - VpcEndpointIds
      # - Label:
      #     default: "Azure to AWS S3 Trigger Lambda Code Settings"
      #   Parameters:
      #     - LambdaS3TriggerKey
      #     - ExistingRoleArn
      #     - TriggerBucket
      # - Label:
      #     default: "Azure to AWS SQS Trigger Lambda Code Settings"
      #   Parameters:
      #     - S3Key
      #     - SQSLambdaExistingRoleArn
      #     - QatchTokenEndpoint
      #     - QatchEndpoint
      #     - QatchS3Bucket

    ParameterLabels:
      Environment:
        default: "Tag for Deployment Environment (dev, alpha, prod)"
      Client:
        default: "Tag for Client "
      Project:
        default: "Primary Project Tag"
      SubProject:
        default: "Sub Project Tag"
      Description:
        default: "Brief description about the project"
      Owner:
        default: "Who is the owner of the project?"
      CreatedBy:
        default: "who creates this resource?"
      PostgresConnectionUSReaderString:
        default: "Postgresql reader connection string(readonly) to use in the lambda to retrieve the data from Qatch US database"
      PostgresConnectionUSWriterString:
        default: "Postgresql writer connection string(readonly) to use in the lambda to retrieve the data from Qatch US database"
      PostgresConnectionCAReaderString:
        default: "Postgresql reader connection string(readonly) to use in the lambda to retrieve the data from Qatch CA database"
      PostgresConnectionCAWriterString:
        default: "Postgresql writer connection string(readonly) to use in the lambda to retrieve the data from Qatch CA database"
      SecretName:
        default: "Name of the secret to be created in AWS Secrets Manager"
      # KmsKeyAlias:
      #   default: "KMS Key Alias for swisscolony client"
      QatchApiAccessKey:
        default: "Access key for Qatch API for the given environment"
      QatchApiAccessSecret:
        default: "Access Secret for Qatch API for the given environment"
      VpcId:
        default: "VPC to associate Lambda with"
      SubnetIds:
        default: "Subnets for Lambda ENIs"
      SecurityGroupIds:
        default: "Security Groups for Lambda ENIs"
      VpcEndpointIds:
        default: "VPC Endpoint IDs for API Gateway Private integration"
      S3Bucket:
        default: "S3 bucket where the lambda packages resides"
      LambdaS3TriggerKey:
        default: "S3 bucket prefix to copy the lambda binary packages"
      ExistingRoleArn:
        default: "Existing Role to be associated in the given lambda"
      QatchS3Bucket:
        default: "Primary Qatch S3 bucket where call recordings are stored"
      TriggerBucket:
        default: "S3 bucket name for the trigger to be configured for Lambda for new Metadata JSON"
      S3Key:
        default: "S3 bucket prefix to copy the lambda binary packages for SQS Lambda"
      SQSLambdaExistingRoleArn:
        default: "Existing ARN Role for SQS Lambda"
      QatchTokenEndpoint:
        default: "Qatch API Token Endpoint"
      QatchEndpoint:
        default: "Qatch API Endpoint"

Parameters:
  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Default: "vpc-08834460b465731a3"
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for Lambda ENIs
    Default: subnet-0a32e71fe797499b6,subnet-0896e97930e347628
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security Groups for Lambda ENIs
    Default: sg-04fe11d44a2a879b2
  VpcEndpointIds:
    Type: List<String>
    Description: VPC Endpoint IDs for API Gateway Private integration
    Default: "vpce-0909347d01c0b50fc"
  Environment:
    Description: Environment type.
    Type: String
    AllowedValues: [dev, prod, qa]
    Default: dev
  Client:
    Description: Client Info.
    Type: String
    AllowedValues: [iqor]
    Default: iqor
  Owner:
    Description: Owner Info.
    Type: String
    AllowedValues: [sathya.ramakrishnan]
    Default: sathya.ramakrishnan
  CreatedBy:
    Description: Creator Info.
    Type: String
    AllowedValues: [ponvel.shanmuganatha, arun.selvan]
    Default: ponvel.shanmuganatha
  UpdatedBy:
    Description: Updator Info.
    Type: String
    AllowedValues: [ponvel.shanmuganatha, arun.selvan]
    Default: ponvel.shanmuganatha
  Project:
    Description: Project Info.
    Type: String
    AllowedValues: [qatch]
    Default: qatch
  SecretName:
    Description: Secret Name.
    Type: String
    AllowedValues: [azure_to_aws]
    Default: azure_to_aws
  PostgresConnectionUSReaderString:
    Type: String
    Default: Server=qatch-db-us-qa-writer.iqor.qor.com;Port=5432;Database=qatch;User Id=qatchappreader;Password=mjY54g0ecNJcD6Km;ApplicationName=Azure_to_AWS_WebApi;timeout=60;
    NoEcho: true                # ensures password is hidden in console/CLI
    Description: US Reader - Secure password input for connectionstring
  PostgresConnectionUSWriterString:
    Type: String
    Default: Server=qatch-db-us-qa-writer.iqor.qor.com;Port=5432;Database=qatch;User Id=qatchappadmin;Password=g0U6137{(Kl6;ApplicationName=Azure_to_AWS_WebApi;timeout=60;
    NoEcho: true                # ensures password is hidden in console/CLI
    Description: US Writer - Secure password input for connectionstring
  PostgresConnectionCAReaderString:
    Type: String
    Default: Server=qatch-db-ca-qa-reader.iqor.qor.com;Port=5432;Database=qatch_qa;User Id=qatchappreader;Password=9V1yQ'2n/8^P;ApplicationName=Azure_to_AWS_WebApi;timeout=60;
    NoEcho: true                # ensures password is hidden in console/CLI
    Description: CA Reader - Secure password input for connectionstring
  PostgresConnectionCAWriterString:
    Type: String
    Default: Server=qatch-db-ca-qa-writer.iqor.qor.com;Port=5432;Database=qatch_qa;User Id=qatchappadmin;Password=j=9r}1[CA102;ApplicationName=Azure_to_AWS_WebApi;timeout=60;
    NoEcho: true                # ensures password is hidden in console/CLI
    Description: CA Writer - Secure password input for connectionstring
  Description:
    Description: Description Info.
    Type: String
    Default: "Copy Azure to AWS REST API"
  SubProject:
    Type: String
    Default: Azure to AWS
    Description: SubProject tag

Globals:
  Function:
    Runtime: dotnet8
    MemorySize: 1024
    Timeout: 30
    Tracing: Active  # Lambda X-Ray tracing

Resources:
  ########################################################################## 
  # Secret storing multiple database connection strings in a single JSON document
  # referenced by application code via SECRET_ID. Update keys atomically here.
  ##########################################################################
  SecretData:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub copy-azure-to-aws/${Environment}/${SecretName}
      Description: !Sub "Azure to AWS Rest Api for ${Environment} environment"
      SecretString: !Sub |
        {
          "ConnectionStrings_USReaderConnection": "${PostgresConnectionUSReaderString}",
          "ConnectionStrings_USWriterConnection": "${PostgresConnectionUSWriterString}",
          "ConnectionStrings_CAReaderConnection": "${PostgresConnectionCAReaderString}",
          "ConnectionStrings_CAWriterConnection": "${PostgresConnectionCAWriterString}"
        }
      Tags:
        - Key: Name
          Value: !Sub SecretData
        - Key: Description
          Value: !Ref Description
        - Key: Environment
          Value: !Ref Environment
        - Key: Client
          Value: !Ref Client
        - Key: CreatedBy
          Value: !Ref CreatedBy
        - Key: UpdatedBy
          Value: !Ref UpdatedBy
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: SubProject
          Value: !Ref SubProject

  ##########################################################################
  # IAM role enabling API Gateway to publish execution logs to CloudWatch
  ##########################################################################
  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub apigw-cwlogs-role-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: apigateway.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  # Associates the account-level CloudWatch Logs role with API Gateway
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn

  ##########################################################################
  # Private REST API fronting the Lambda (proxy integration, VPC endpoint restricted)
  ##########################################################################
  RestApiPrivate:
    Type: AWS::Serverless::Api
    Properties:
      Name: copy-azure-to-aws-rest-private
      StageName: !Ref Environment
      EndpointConfiguration:
        Type: PRIVATE
        VpcEndpointIds: !Ref VpcEndpointIds
      TracingEnabled: true
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt RestApiAccessLogs.Arn
        Format: '{ "requestId":"$context.requestId","ip":"$context.identity.sourceIp","caller":"$context.identity.caller","user":"$context.identity.user","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath","status":$context.status,"protocol":"$context.protocol","responseLength":"$context.responseLength","integrationStatus":"$context.integrationStatus","integrationError":"$context.integrationErrorMessage","xrayTraceId":"$context.xrayTraceId" }'
      Auth:
        ResourcePolicy:
          CustomStatements:
            - Effect: Allow
              Principal: "*"
              Action: execute-api:Invoke
              Resource: execute-api:/*/*/*
              Condition:
                StringEquals:
                  aws:SourceVpce:
                    - vpce-0909347d01c0b50fc
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: copy-azure-to-aws-rest-private
          version: '1.0'
        paths:
          /:
            x-amazon-apigateway-any-method:
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebApiFunction.Arn}/invocations
          /{proxy+}:
            x-amazon-apigateway-any-method:
              parameters:
                - name: proxy
                  in: path
                  required: true
                  schema: { type: string }
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebApiFunction.Arn}/invocations
      Tags:
        Name: copy-azure-to-aws-rest-private
        Description: !Ref Description
        Environment: !Ref Environment
        Client: !Ref Client
        CreatedBy: !Ref CreatedBy
        UpdatedBy: !Ref UpdatedBy
        Owner: !Ref Owner
        Project: !Ref Project
        SubProject: !Ref SubProject

  ##########################################################################
  # Lambda handling API requests (producer of SQS messages later if wired)
  ##########################################################################
  WebApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: copy-azure-to-aws-api-private
      CodeUri:
        Bucket: awsuse1dev2stiqor01
        Key: lambdas/Azure_to_AWS/CopyAzureToAWS.Api.zip
      Handler: CopyAzureToAWS.Api::CopyAzureToAWS.Api.LambdaEntryPoint::FunctionHandlerAsync
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            - Effect: Allow
              Action: sqs:SendMessage
              Resource: !GetAtt CopyAzureToAWSRequestQueue.Arn
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource: !Ref SecretData
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIds
      Environment:
        Variables:
          SECRET_ID: !Sub copy-azure-to-aws/${Environment}/${SecretName}
          GetExtendedDataUsersCache: "dbo.fn_get_extended_data_users_cache|Reader"
          GetJwtTokenKey: "dbo.fn_get_jwt_token_key|Reader"
          RecordAzureToAWSStatus: "dbo.usp_record_azure_to_aws_status|Writer"
          AWS__SQS__QueueUrl: !Ref CopyAzureToAWSRequestQueue
          Logging__LogLevel__Default: Information         # optional
          Logging__LogLevel__CopyAzureToAWS: Information  # optional namespace tuning
      Events:
        ApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiPrivate
            Path: /
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiPrivate
            Path: /{proxy+}
            Method: ANY
      Tags:
        Name: copy-azure-to-aws-api-private
        Description: !Ref Description
        Environment: !Ref Environment
        Client: !Ref Client
        CreatedBy: !Ref CreatedBy
        UpdatedBy: !Ref UpdatedBy
        Owner: !Ref Owner
        Project: !Ref Project
        SubProject: !Ref SubProject

  ##########################################################################
  # Permission allowing API Gateway to invoke the Lambda integration
  ##########################################################################
  ApiInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebApiFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiPrivate}/*/*/*

  ##########################################################################
  # Dedicated log group with retention for WebApiFunction
  ##########################################################################
  WebApiFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${WebApiFunction}
      RetentionInDays: 90

  ##########################################################################
  # Access log destination for API Gateway stage
  ##########################################################################
  RestApiAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${RestApiPrivate}
      RetentionInDays: 90

  ###########################################################################
  # NEW: Dead-letter FIFO queue for failed copy requests
  ###########################################################################
  CopyAzureToAWSRequestQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: copy-azure-to-aws-request-dlq.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      MessageRetentionPeriod: 1209600

  ###########################################################################
  # NEW: Primary FIFO queue for copy requests
  ###########################################################################
  CopyAzureToAWSRequestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: copy-azure-to-aws-request.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CopyAzureToAWSRequestQueueDLQ.Arn
        maxReceiveCount: 5

  ###########################################################################
  # NEW: Processor Lambda consuming the primary queue
  ###########################################################################
  CopyProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: copy-azure-to-aws-processor
      CodeUri:
        Bucket: awsuse1dev2stiqor01
        Key: lambdas/Azure_to_AWS/CopyAzureToAWS.Lambda.zip
      Handler: CopyAzureToAWS.Lambda::CopyAzureToAWS.Function::FunctionHandler
      Runtime: dotnet8
      MemorySize: 1536
      Timeout: 180
      Tracing: Active
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIds
      Environment:
        Variables:
          SECRET_ID: !Sub copy-azure-to-aws/${Environment}/${SecretName}
          SOURCE_SYSTEM: "AZURE"
          TARGET_SYSTEM: "AWS"
          QUEUE_URL: !Ref CopyAzureToAWSRequestQueue
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - sqs:ChangeMessageVisibility
              Resource: !GetAtt CopyAzureToAWSRequestQueue.Arn
            - Effect: Allow
              Action:
                - sqs:GetQueueAttributes
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
              Resource: !GetAtt CopyAzureToAWSRequestQueueDLQ.Arn
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource: !Ref SecretData
      Events:
        CopyQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt CopyAzureToAWSRequestQueue.Arn
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 0
            Enabled: true

Outputs:
  # Core API + secret identifiers
  ApiId:
    Value: !Ref RestApiPrivate
    Description: API Gateway REST API Id (PRIVATE)
  ApiInvokeUrl:
    Value: !Sub https://${RestApiPrivate}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
    Description: Invoke URL (reachable only via the specified VPC endpoint)
  SecretName:
    Value: !Sub copy-azure-to-aws/${Environment}/${SecretName}
  SecretArn:
    Value: !Ref SecretData
  # Messaging and processing outputs for observability and wiring other stacks
  PrimaryQueueUrl:
    Value: !Ref CopyAzureToAWSRequestQueue
  PrimaryQueueArn:
    Value: !GetAtt CopyAzureToAWSRequestQueue.Arn
  DLQQueueUrl:
    Value: !Ref CopyAzureToAWSRequestQueueDLQ
  DLQQueueArn:
    Value: !GetAtt CopyAzureToAWSRequestQueueDLQ.Arn
  ProcessorFunctionName:
    Value: !Ref CopyProcessorFunction